---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/charts/rabbitmq
      sourceRef:
        kind: GitRepository
        name: code-infra
  interval: 10m0s

